#!/usr/bin/env bash
# Full production deployment with Docker Compose.
#
# Prerequisites: Docker + Docker Compose
#
# Usage:
#   ./scripts/deploy.sh
#
# What it does:
#   1. Creates root .env with secrets if missing
#   2. Ensures JWT keys exist (runs setup-jwt.sh if needed)
#   3. Builds and starts docker-compose.prod.yml
#   4. Waits for /api/health

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
COMPOSE_FILE="${ROOT_DIR}/docker-compose.prod.yml"
JWT_PRIVATE="${ROOT_DIR}/api/config/jwt/private.pem"
FRONT_PORT="${FRONT_PORT:-80}"

cd "$ROOT_DIR"

if ! command -v docker >/dev/null 2>&1; then
  echo "Error: docker is required." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Error: docker compose is required." >&2
  exit 1
fi

load_env() {
  if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    set -a && source "$ENV_FILE" && set +a
  fi
  FRONT_PORT="${FRONT_PORT:-80}"
}

ensure_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    echo "Environment file: ${ENV_FILE}"
    return
  fi

  echo "Creating ${ENV_FILE} with generated secrets..."
  local mysql_root mysql_user mysql_pass app_secret jwt_pass

  mysql_root="$(openssl rand -hex 16)"
  mysql_user="petanque"
  mysql_pass="$(openssl rand -hex 16)"
  app_secret="$(openssl rand -hex 16)"
  jwt_pass="$(openssl rand -base64 24)"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy.sh — adjust for your server.
MYSQL_ROOT_PASSWORD=${mysql_root}
MYSQL_DATABASE=petanque
MYSQL_USER=${mysql_user}
MYSQL_PASSWORD=${mysql_pass}

APP_SECRET=${app_secret}
JWT_PASSPHRASE=${jwt_pass}

FRONT_PORT=80
CORS_ALLOW_ORIGIN=http://localhost
EOF

  chmod 600 "$ENV_FILE"
  echo "Created ${ENV_FILE} (JWT_PASSPHRASE stored inside — keep this file safe)."
}

ensure_jwt_keys() {
  if [[ -f "$JWT_PRIVATE" ]]; then
    echo "JWT keys: OK"
    return
  fi

  if [[ -z "${JWT_PASSPHRASE:-}" ]]; then
    echo "Error: JWT_PASSPHRASE is not set. Add it to ${ENV_FILE} or export it." >&2
    exit 1
  fi

  echo "JWT keys not found — running setup-jwt.sh..."
  JWT_PASSPHRASE="${JWT_PASSPHRASE}" "${ROOT_DIR}/scripts/setup-jwt.sh"
}

wait_for_health() {
  local health_url="http://localhost:${FRONT_PORT}/api/health"
  echo "Waiting for API health at ${health_url} ..."

  if ! command -v curl >/dev/null 2>&1; then
    echo "curl not found — skipping health check."
    return 0
  fi

  for _ in $(seq 1 60); do
    if curl -sf "$health_url" >/dev/null 2>&1; then
      echo "API is healthy."
      curl -s "$health_url"
      echo
      return 0
    fi
    sleep 2
  done

  echo "Error: API did not become healthy in time." >&2
  echo "Check logs: docker compose -f docker-compose.prod.yml logs api" >&2
  exit 1
}

echo "=== Pétanque Analytics — deploy ==="
echo ""

ensure_env_file
load_env
ensure_jwt_keys

echo ""
echo "Starting production stack..."
docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build

echo ""
wait_for_health

echo ""
echo "Deploy complete."
echo "  Front:  http://localhost:${FRONT_PORT}"
echo "  Health: http://localhost:${FRONT_PORT}/api/health"
echo ""
echo "Logs:  docker compose -f docker-compose.prod.yml logs -f"
echo "Stop:  docker compose -f docker-compose.prod.yml down"
